### PR TITLE
[P3 tests] [Team 18] Phrase Search Tests 

### PR DESCRIPTION
**Pull request by mengqiwangwmq**
What's your team number?
Team 18

What is the functionality being tested?
Phrase Search

Describe your tests briefly:

test1 tests if there is a "," between two consecutive words of one phrase in a document, the document will not be chosen as a search result, and it also tests if there are stop words between two consecutive words of one phrase in a document, the document will be chosen as a search result.

test2 tests if phrase search applies to cases with more or equal than 3 words in a single phrase.

test3 tests if phrase search spans in multiple segments and merged segments.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by omidkv** [comment]
Team 14 Review:

Your tests look good. We do think that there is an issue in your first test. Why doesn't the document that has a comma between test and cases get added to the expected results? When we tokenize the comma should be removed. And there isn't another token between test and cases.

Test 2 looks good to us.

 I think that in test 3 the document that starts "Even though" should also be an expected result for the same reasons as it should be in test1 expected.

**Comment by mengqiwangwmq** [comment]
> Team 14 Review:
> 
> Your tests look good. We do think that there is an issue in your first test. Why doesn't the document that has a comma between test and cases get added to the expected results? When we tokenize the comma should be removed. And there isn't another token between test and cases.
> 
> Test 2 looks good to us.
> 
> I think that in test 3 the document that starts "Even though" should also be an expected result for the same reasons as it should be in test1 expected.
However, I just think that in reality, "test, case" cannot be the answer users want, since there is no correlation between "test" and "case". Actually, I am quite confused about this, too.

**Comment by yhx1** [comment]
Team 17 Review:

Solid test cases. I, too, thinks "test, case" should appear in the search result. The project page explicitly says we are using token positions instead of character positions, so I guess "test, case" appears to be the same as "test case" after going through PunctuationTokenizer.

**Comment by mengqiwangwmq** [comment]
That makes sense. I'll modify the test cases. Thanks!

**Pull request merged**
