### PR TITLE
[P1 tests] [Team 5] Add Punctuation Tokenizer Tests

### PR DESCRIPTION
**Pull request by shaheming**
### Team 5 Punctuation Tokenizer

1. test ,? split, ignoring stop words and uppercase to lowercase transfer
2. test ! . split, ignoring stop words and uppercase to lowercase transfer
3. test empty input
4. test more than one spaces input
5. test more than one spaces with word
6. test only punctuations
7. test no stop words
8. test all stop words and punctuations
9. test punctuations that should not be removed

### CODE REVIEW

**Comment by ZTShao** [comment]
I think you should only add the testcases file and commit it rather than add the whole project because this may include other codes that you have modified such as the punctuationtokenizer.java. If there are other files added then we cannot merge your files. So I suggest you withdraw your pull request and ONLY add the testcase file to the github.

**Comment by ZTShao** [comment]
For your test cases I think they are perfect and almost covering all the edge cases! Especially for the one that you want to test all the stop words and punctuations.

**Comment by Haixiang6123** [comment]
Your test cases are almost covering all the situations, such as testing empty string and a very long string, so good work! Just a remind, you'll better not commit the source codes, because Prof wants all repos are private and the source codes are not public to others. My suggestion is to open another private repo and commit your source codes there:), whereas this repo is not for wiring test cases.

**Comment by chenghz4** [comment]
Already fixed that

**Comment by zhongwew** [comment]
Good job! I think the testcases have covered most of the corner cases and are ready for merge. It would be better if adding some comments in the code.

**Pull request merged**
