### PR TITLE
[P2 tests] [Team 18] Add Task 1 Flush Tests

### PR DESCRIPTION
**Pull request by mengqiwangwmq**
What's your team number?
Team 18

What is the functionality being tested?
Task 1: Flush and Read Segments (no merge)

Describe your tests briefly:
test1 tests given flush() called and document number not exceeding flush threshold, getNumSegment() and getDocuments() function or not.
test2 tests given no document added and flush() called getNumSegment() and getDocuments() function or not.
test3 tests given number of documents exceeding flush threshold, flush() is called automatically and getNumSegment() and getDocuments() function or not.
clear() use Junit @After to delete all written files after each test.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by adslchen** [comment]
Team 22 review:

For test2()
If the segment doesn't exist, the `InvertedIndexSegmentForTest iiTestSegment = manager.getIndexSegment(0);` would return null pointer.

For all test case
The `docID` might not be in order, so the assert function about docID might be inappropriate.

**Comment by yhx1** [comment]
Team 17 review: 

Solid test cases, but same problem as Team 22 said, in test 2 iiTestSegment will be null.
I don't think docID must be in order, so the sorting in test3() seems necessary.

**Comment by mengqiwangwmq** [comment]
Have updated test2, thanks for mentioning this.
And one more question, since iiTestSegment is null, there is no need to compare the invertedLists and documents cause they will not be initialized, is that correct?

**Comment by adslchen** [comment]
@mengqiwangwmq  Yup, I believe that. No need to compare the invertedLists anymore.

**Pull request merged**
