### PR TITLE
[P1 tests] [Team 9] Add Word Break Tokenizer Tests

### PR DESCRIPTION
**Pull request by Xiaowo857**
What's your team number? Team 9

What is the functionality being tested? Wordbreak Tokenizer

Describe your tests briefly: 
test1 tests if the tokenizer handles empty input. 
test2 tests for upper case input.
test3 tests cases which have multiple answers.
test4 tests invalid input, expect an exception. Exception type depends on the implementation.

Does each test case have comments/documentation? 
Yes

### CODE REVIEW

**Comment by TLizzie** [comment]
We think your test cases are detailed and look good :)

Team 8

**Comment by hard-fault** [comment]
Review from Team 17:

I would like to point out a syntax error.

must have been,
List<String> expected = Arrays.asList("i", "like", "information", "retrieval");

instead you are using:
List<String> expected = Arrays.asList("i like information retrieval");

**Comment by DanniUCI** [comment]
> Review from Team 17:
> 
> I would like to point out a syntax error.
> 
> must have been,
> List expected = Arrays.asList("i", "like", "information", "retrieval");
> 
> instead you are using:
> List expected = Arrays.asList("i like information retrieval");

Thanks for reviewing our test cases. This issue was already repaired several days ago. Could you please check our latest version? Thanks!

**Comment by hard-fault** [comment]
> > Review from Team 17:
> > I would like to point out a syntax error.
> > must have been,
> > List expected = Arrays.asList("i", "like", "information", "retrieval");
> > instead you are using:
> > List expected = Arrays.asList("i like information retrieval");
> 
> Thanks for reviewing our test cases. This issue was already repaired several days ago. Could you please check our latest version? Thanks!

That's great! Otherwise, there are no problems :)

**Comment by sadeemsaleh** [comment]
Our team is not supposed to review the testcases but our code didn't pass test1() and test3() for the below reasons.
I think test1() should return an empty list not a list of an empty string as one token
test3() should expect a runTimeException as mentioned in class not illegal argument exception.

**Pull request merged**
