### PR TITLE
[P4 tests] [Team 20] Add searchTfIdf Tests

### PR DESCRIPTION
**Pull request by pridawn**
What's your team number?
Team 20

What is the functionality being tested?
searchTfIdf()

Describe your tests briefly:
Test1 tests if the Top K documents are returned in the expected order.
Test2 tests whether the documents are ranked in the correct order when the no. of documents in the index is less than the no of documents asked for in the query.
Test3 tests whether all the documents are ranked in the correct order when the no of documents
 asked for in the query is null.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by mengqiwangwmq** [comment]
Solid and comprehensive test cases. Test case2 is pretty ingenious to ask for more documents than the actual result.

**Comment by NinoXing** [comment]
Hi, as TA has mentioned in Slack: _"It’s not needed to fill in topK using documents that don’t match the query (tf-idf score 0). If there are less than k, you could just return them."_ , I think in test1 and test2 the iterator should not return doc2 which does not match the query.

**Comment by Nedhoven** [comment]
Review from team#19:

Also agreed with the fact that doc2 should not be returned as the result of the search! Other than that, test cases look solid!

**Comment by pridawn** [comment]
removed doc2 being returned from the search queries in tests as per the reviews

**Pull request merged**
