### PR TITLE
[P1 tests] [Team 1] Add Punctuation Tokenizer Tests

### PR DESCRIPTION
**Pull request by LaytonW**
#### What's your team number?
Team 1

#### What is the functionality being tested?
Punctuation Tokenizer

#### Describe your tests briefly:
- `whiteSpacesShouldDelimit`: Test whether the punctuation tokenizer handles white spaces correctly.
- `punctuationsShouldDelimit`: Test whether the punctuation tokenizer handles punctuations correctly.
- `nonDelimiterShouldNotDelimit`: Test whether the punctuation tokenizer handles non-delimiter characters correctly.
- `tokensShouldBeLowerCase`: Test whether the punctuation tokenizer converts tokens into lower cases.
- `consecutiveWhiteSpacesShouldDelimit`: Test whether the punctuation tokenizer correctly handles consecutive whitespace characters.
- `consecutivePunctuationsShouldDelimit`: Test whether the punctuation tokenizer correctly handles consecutive punctuations.
- `surroundingWhiteSpacesShouldBeRemoved`: Test whether the punctuation tokenizer correctly handles leading and trailing whitespace characters.
- `surroundingPunctuationsShouldBeRemoved`: Test whether the punctuation tokenizer correctly handles leading and trailing punctuations.
- `stopWordsShouldBeRemoved`: Test whether the punctuation tokenizer correctly handles stop words.
- `integrationTest`: Integrated test case to check whether the punctuation tokenizer jointly satisfies all requirements tested above.

#### Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by FuyaoLi2017** [comment]
### Review from Team 1
I have checked the test cases, I think they looks good to me! Good job!

**Comment by LaytonW** [comment]
> ### Review from Team 1
> I have checked the test cases, I think they looks good to me! Good job!

@FuyaoLi2017  Thanks! 🎉

BTW, aren't you from team 2? I thought I was in team 1 😂 
Also, you probably want to check [the Google Spreadsheet](https://docs.google.com/spreadsheets/d/1_iwJOT-bnYDk9tWNNy61GCyi1kRN7s3VHdn5h_2T1DA/edit#gid=265881081) to see which two other teams are assigned to you for reviewing.

**Comment by FuyaoLi2017** [comment]
> > ### Review from Team 1
> > I have checked the test cases, I think they looks good to me! Good job!
> 
> @FuyaoLi2017 Thanks! 🎉
> 
> BTW, aren't you from team 2? I thought I was in team 1 😂
> Also, you probably want to check [the Google Spreadsheet](https://docs.google.com/spreadsheets/d/1_iwJOT-bnYDk9tWNNy61GCyi1kRN7s3VHdn5h_2T1DA/edit#gid=265881081) to see which two other teams are assigned to you for reviewing.

Haha, it is a typo. I am from team 2. I have reviewed the google spread sheet. Thanks!

**Comment by NinCors** [comment]
Sophisticated test plan and detailed explanation. I think those tests are ready to be merged.

**Pull request merged**
