### PR TITLE
[P3 tests] [Team 7] Task3: Compare Index with Compression

### PR DESCRIPTION
**Pull request by NinCors**
What's your team number?
Team 07

What is the functionality being tested?
Compare Index with Compression

Describe your tests briefly:
`addFewDocument` tests if the compression ratio right when adding a small number of documents.

`addLargeDocument` tests if the compression ratio right when adding a large number of documents.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by chenghz4** [comment]
nice work! But it would have been nicer if you had used a more reasonable ratio for checking the compression instead of just using 1. For example naive readcounter>1.4 compression read counter would be better.

Also if you guys could check the compression of inverted list and positional list separately, it would be better.

**Comment by NinCors** [comment]
> nice work! But it would have been nicer if you had used a more reasonable ratio for checking the compression instead of just using 1. For example naive readcounter>1.4 compression read counter would be better.
> 
> Also if you guys could check the compression of inverted list and positional list separately, it would be better.

**Comment by NinCors** [comment]
> nice work! But it would have been nicer if you had used a more reasonable ratio for checking the compression instead of just using 1. For example naive readcounter>1.4 compression read counter would be better.
> 
> Also if you guys could check the compression of inverted list and positional list separately, it would be better.

Thx for the comment. I changed the ratio to 1.4. However, I don't think it is necessary to test it separately since there is no logical difference.

**Comment by MarlonCZY** [comment]
Nice work. I think it will be better you should also test the readCounter as well as test some cases like empty documents.

**Pull request merged**
