### PR TITLE
[P2 tests][Team 17]Add Task 1 Flush Tests

### PR DESCRIPTION
**Pull request by yhx1**
What's your team number?
Team 17

What is the functionality being tested?
Part 1, namely addDocument, flush, getNumSegments, getIndexSegment

Describe your tests briefly:
**testInit** tests if getNumSegments() and getIndexSegment() work properly when creating a new folder.
**testAddDocumentFlush** tests if explicit call to flush() creates a disk segment correctly.
**testAutoFlush** tests if when flush threshold is reached, a segment is automatically created; also tests the correctness of such segment. 1000 documents of the same contents are added in the segment.
**testMixedDocumentAndFlush** tests if adding documents with different content works properly when explicit flush and automatic flush work properly together. 500 documents of 2 kinds are added in the second segment.
**testFlushEmptyBuffer** tests if calling flush() when buffer is empty will crash the program.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by sriting** [comment]
Team 21 Review

It seems that you forget to clean up and delete all files after each test. You should use Junit @After to delete all written files written in 'index' file as the second point of test case requirements. Besides, it looks good to me.

**Comment by sriting** [comment]
Additional review from team 21 :

I believe the location of the test file should be `src/test/java/edu/uci/ics/cs221/index/inverted/XXX.java`.

**Comment by CKRC24** [comment]
Team 22 Review
For the design part I think is pretty fine, only some few problems:
1. In all test cases, you supposed the document ID starts from "0". However, document ID should be local to each segment, so I think you should not directly build up an expectedList. You should use Set to examine whether all documents are correctly retrieved.
2. In **testMixedDocumentAndFlush**, I think the size of both keywords "auto" and "base" should be 500 instead of 1000 (which is the default_flush_threshold).
3. You should put your deletion code in the Junit @After section.

**Comment by yhx1** [comment]
> 
> 
> Additional review from team 21 :
> 
> I believe the location of the test file should be `src/test/java/edu/uci/ics/cs221/index/inverted/XXX.java`.

I added cleanup function. I think somewhere on Slack our TA mentions the test file should be placed in ./index folder, that's why I'm using ./index/Team17 to not to interfere with other team's files.

**Comment by sriting** [comment]
> > Additional review from team 21 :
> > I believe the location of the test file should be `src/test/java/edu/uci/ics/cs221/index/inverted/XXX.java`.
> 
> I added cleanup function. I think somewhere on Slack our TA mentions the test file should be placed in ./index folder, that's why I'm using ./index/Team17 to not to interfere with other team's files.

TA said that the files generated for segment can be stored in `./index` folder as the same level of 'src' folder. But I think the test file needs to be written in `src/test/java/edu/uci/ics/cs221/index/inverted/XXX.java`, which is same structure to src files.

**Comment by sriting** [comment]
I agree with team 22. The document ID should be local and should not be called in test case. I recommend you to modify the code.

**Pull request merged**
