### PR TITLE
[P1 tests] [Team 14] Add Word Breaker Tokenizer Tests

### PR DESCRIPTION
**Pull request by omidkv**
Merge team 14 test cases to the base project

### CODE REVIEW

**Comment by YuehWu1994** [comment]
You should add a comment on pull request, check this [template](https://github.com/UCI-Chenli-teaching/spring19-cs221-project/pull/1).

**Comment by YuehWu1994** [comment]
You should follow the template of comment at [this link](https://github.com/UCI-Chenli-teaching/spring19-cs221-project/pull/1).

**Comment by omidkv** [comment]
What's your team number?
Team 14

What is the functionality being tested?
Wordbreak Tokenizer

Describe your tests briefly:
test1 tests if the tokenizer handles a string that can't be broken.
test2 tests if the tokenizer can handle a string with multiple stop words and multiple types of casing


Does each test case have comments/documentation?
Yes

**Comment by zerowei** [comment]
Test cases look fine. But in the requirements of task 2, we are also asked to find the optimal way when there are many alternatives to break a string. So I think it's better for you to write a test case on that which has several combinations of text and we choose the best one. Besides, you can also write a test case on punctuation check. It was discussed on Slack so maybe it's good choice to include it.

Team 11

**Comment by YuehWu1994** [comment]
Yap, you could also add spaces (space, tab, newline) check to throw an exception while the text contains spaces.

Team 12

**Comment by omidkv** [comment]
Commit ee22373 fixes an error in the expected output of our string. Initially, we assumed that the word breaker would split "behaving" into "be" and "having" however after looking at the probabilities the probability that it is split into "be" and "having" is 8.942270843999999E-7 and for "behaving" it is 1.52E-6. Which means that the sentence will be split in to "behaving" instead of "be" and "having"

**Pull request merged**
