### PR TITLE
[P1 tests] [Team 23] Added Porter Stemmer Testcases

### PR DESCRIPTION
**Pull request by sgsvenkatesh**
Team Number: **Team 23**

Functionality: **Porter Stemmer**

Description:
`test1` - covers the words which should be modified (or should not be falsely modified) by steps 1a, 1b, 1b-cleanup, 1c of Porter Stemmer
`test2` - covers the words which should be modified (or should not be falsely modified) by step 2 of Porter Stemmer
`test3` - covers the words which should be modified (or should not be falsely modified) by step 3 of Porter Stemmer
`test4` - covers the words which should be modified (or should not be falsely modified) by step 4 of Porter Stemmer
`test5` - covers the words which should be modified (or should not be falsely modified) by steps 5a, 5b of Porter Stemmer

Documentation: **Yes**

### CODE REVIEW

**Comment by nevedharavi** [comment]
All the test cases look good and passed.

**Comment by pridawn** [comment]
Review from team 20: This is trivial but maybe you could change the name of your test cases to something less generic..:)

**Comment by sgsvenkatesh** [comment]
Thanks for your review. 
I'm sorry but I'm unsure what do you mean by name of the test case.

**Comment by CKRC24** [comment]
Review from team 22: I like the idea of breaking down the test cases to examine each step of the Porter Stemming algorithm, all works well.

**Comment by pridawn** [comment]
I meant the name of the test methods. Ignore what I said..because I can't think of any instance when you would want to run the method individually.. All looks good.

**Pull request merged**
