### PR TITLE
[P1 tests] [Team 17] Add Wordbreak Tokenizer Tests

### PR DESCRIPTION
**Pull request by hard-fault**
What's your team number?
Team 17

What is the functionality being tested?
Wordbreak Tokenizer

Describe your tests briefly:
**test1** tests if the tokenizer handles combination tokens with mixed cases. 
**test2** tests if the tokenizer can handle really large strings and stop words efficiently.
**test3** has an empty string
**test4** has a punctuation in the string and the wordbreak tokenizer must throw an exception.
**test5** has two possible set of tokens. The wordbreak tokenizer must come up with the most optimal one.

Does each test case have comments/documentation?
Yes

> > 1. test5() should be tokenized to "hell", "orange" because "range" is not in the dictionary
> 
> "range" is in the dictionary : range 128314924

That'r right! range is present in the dictionary. @sadeemsaleh

### CODE REVIEW

**Comment by NinoXing** [comment]
> 3. test5() should be tokenized to "hell", "orange" because "range" is not in the dictionary

"range" is in the dictionary : range 128314924

**Comment by mlychagin** [comment]
Review from Team14

Change IllegalArgumentException.class to RuntimeException.class in Test4.
Other than that, there are no glaring issues after you addressed Team12's comments.
"range" is indeed in the dictionary.

**Comment by zuozhiw** [comment]
@hard-fault please change your test case file name to follow our naming convention, `Team17 WordBreakTokenizerTest`, otherwise I cannot merge your file.

**Comment by hard-fault** [comment]
> @hard-fault please change your test case file name to follow our naming convention, `Team17 WordBreakTokenizerTest`, otherwise I cannot merge your file.

Sorry about the confusion. I have rectified the class name.

**Pull request merged**
