### PR TITLE
[P1 tests] [Team 22] Add Porter Stemmer Tests

### PR DESCRIPTION
**Pull request by adslchen**
What's your team number?
Team 22
What is the functionality being tested?
Porter Stemmer

Describe your tests briefly:
test1 tests if the stemmer stems words end with "ible", "ize" and "ion" as well as words in the past tense.
test2 tests if the stemmer stems words end with "fully", "ator", "ment", "ness" and "ing".
test3 tests if the stemmer stems words end with "ance", "ate", "y", "val" and "ism".
Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by nevedharavi** [comment]
Porter Stemmer stems 'one' to make it 'on'. I ran these tests , this seems to be the only problem :

org.junit.ComparisonFailure:
Expected :thi wall is regard as one of the indestruct construct in ancient time which wa built with marbl in standard size and design by smartest scientist at that time
Actual :thi wall is regard as on of the indestruct construct in ancient time which wa built with marbl in standard size and design by smartest scientist at that time

**Comment by Nedhoven** [comment]
Review form Team 19:

The test case #1 does not pass. Here is the details:
'''Expected :thi wall is regard as one of the indestruct construct in ancient time which wa built with  marbl in standard size and design by smartest scientist at that time
Actual   :thi wall is regard as on of the indestruct construct in ancient time which wa built with marbl in standard size and design by smartest scientist at that time'''

The test case #2 does not pass and here is the result:
'''Expected :hope the refriger start work again in that chen li made some adjust with care
Actual   :hopefulli the refriger start work again in that chen li made some adjust with care'''

The test case #3 passes the PorterStemmer tests.

**Comment by adslchen** [comment]
@Nedhoven I think test case 2 is correct.  I tried Lucene version porter stemmer as well as applied the [algorithm](http://snowball.tartarus.org/algorithms/porter/stemmer.html) this the word "hopefully" becomes "hopefulli", while nltk version yield "hope". I think we should stick with Lucene version?

**Comment by pridawn** [comment]
Review from team 20: This is trivial but maybe you could change the name of your test cases to something less generic..

**Pull request merged**
