### PR TITLE
[P2 tests] [Team 6] Add Overall: Boolean And Search Test

### PR DESCRIPTION
**Pull request by zhongwew**
Finished test cases for And search:
test1: test if normal input and output can work correctly
test2: test empty input and output
test3: test large word list
test4: test if exceptions could be correctly thrown when no element could be found

### CODE REVIEW

**Comment by shaheming** [comment]
The test cases cover the some basic points. But there are some problems.



1. You test case can not  check whether the searching results is right or not . Take the  `test1` for example. If your searchQuery return doc3 that do not contain  any keywords, your test case will not throw error. **All of your testcases have this problem.**

```Java
Set<Document> docs = new HashSet<Document>();
Document doc1 = new Document("dog, bone and fishes");
docs.add(doc1);
indexM.addDocument(doc1);
Document doc2 = new Document("cats, fishes and dogs");
docs.add(doc2);
indexM.addDocument(doc1);
Document doc3 = new Document("fishes, birds and sky");
docs.add(doc3);
indexM.addDocument(doc1);
Document doc4 = new Document("cats, bones and something");
docs.add(doc4);
indexM.addDocument(doc1);

List<String> keyWords = Arrays.asList("cat", "bone");

Iterator<Document> ite = indexM.searchAndQuery(keyWords);

while(ite.hasNext()){
assertEquals(true, docs.contains(ite.next()));
}
```

2. You should` flush()` the invertlist's segment to disk before you search the keywors.
3. In test2,  the `searchAndQuery` will throw ` NullPointerException()` instead of empty result.

4. This code will throw error, if the directory do not exit.  You should try to create this directory before  creating or open the indexmanager.

```Java
InvertedIndexManager indexM = InvertedIndexManager.createOrOpen("./index/Team6AndSearchTest", analyzer);
```

4. As for test4, the ite.next() will throw error if there do not exit next item. This  is the iterator's property. I think you should test that all the document do not match the searchquery, and assert `iterator.hasNext() == false`.
5. Pealse do not  change  other files. You can checkout the teach-rep/master  branch and then add your test code, push it -f to your current branch. And you should fix all conflicts before creating a merge request.

**Comment by shaheming** [comment]
> This branch has conflicts that must be resolved
> Only those with write access to this repository can merge pull requests.
You should solve the conflicts.

**Comment by hanluc** [comment]
It seems good to me after modifications. I think they are ready for merge.

**Comment by NinoXing** [comment]
I think there is a little problem with test3(). 
Because you use *__Analyzer analyzer = new ComposableAnalyzer(new WordBreakTokenizer(), new PorterStemmer());__*, then there will never be a keyword "apple". 
"apple" becomes "appl" because of the PorterStemmer.

**Comment by zuozhiw** [comment]
@NinoXing keywords in the search query need to be analyzed using the analyzer as well, so this test is correct.

**Comment by NinoXing** [comment]
> @NinoXing keywords in the search query need to be analyzed using the analyzer as well, so this test is correct.

Oh, my bad

**Pull request merged**
