### PR TITLE
[P1 tests] [Team 11] Add WordBreak Tokenizer Tests

### PR DESCRIPTION
**Pull request by ruig2**
What's your team number?
Team 11

What is the functionality being tested?
Wordbreak Tokenizer

Describe your tests briefly:
Test 1: Test with a sentence that is only made up of stop words
Test 2: Empty input test
Test 3: Input string cannot be tokenized, an UnsupportedOperationException is expected
Test 4: Test with a normal case: it can be tokenized
Test 5: Test with a few upper cases
Test 6: Test with all upper cases
Test 7: Test with stop word at the beginning
Test 8: Test with stop word in the middle
Test 9: Testwith stop word in the end

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by Andresheep** [comment]
> What's your team number?
> Team 8
> 
> What is the functionality being tested?
> Wordbreak Tokenizer
> 
> Describe your tests briefly:
> Test 1: Test with a sentence that is only made up of stop words
> Test 2: Empty input test
> Test 3: Input string cannot be tokenized, an UnsupportedOperationException is expected
> Test 4: Test with a normal case: it can be tokenized
> Test 5: Test with a few upper cases
> Test 6: Test with all upper cases
> Test 7: Test with stop word at the beginning
> Test 8: Test with stop word in the middle
> Test 9: Testwith stop word in the end
> 
> Does each test case have comments/documentation?
> Yes

As the reviewer, I'm confused whether u r team8 or team 11 :)

**Comment by ruig2** [comment]
@Andresheep Thx for the reminder. I've updated the above comment. ;)

**Comment by KaifuJ** [comment]
A very complete set of test cases!
It would be better if more words could be used in the tests, rather than just modifications to "searchnewtimeuse".
Also, personally, I think if the WordBreak Tokenizer is implemented in the way that it first breaks texts into strings and then remove stop words, there will be not much difference between test case 7/8/9.

**Comment by DanniUCI** [comment]
All the test cases are correct and clear~

Team 9

**Pull request merged**
