### PR TITLE
[P1 tests] [Team 8] Add WordBreak Tokenizer Tests

### PR DESCRIPTION
**Pull request by TLizzie**
What's your team number?
Team 8

What is the functionality being tested?
Wordbreak Tokenizer

Describe your tests briefly:
test1 tests if the output is lower cased and stop words are removed.
test2 tests if the program can handle strings like "whatevergreen" and string consists of more than one frequently used words.
test3 tests if the program can throw an exception when string is unbreakable.

Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by hard-fault** [comment]
Review from Team 17:
test1 should throw an exception as the apostrophe isn't an expected symbol for the wordbreak tokenizer. The TA clarified this on slack.

**Comment by NinoXing** [comment]
> Review from Team 17:
> test1 should throw an exception as the apostrophe isn't an expected symbol for the wordbreak tokenizer. The TA clarified this on slack.

Hi, thank you for advice~
Do you mean the TA said on slack that "If the input contains punctuations, then your algorithm should not find any possible way and then throw an exception"? However, the apostrophe is not among punctuations, and also there are several words like "i'm 300000", "couldn't 300000" and "can't 300000" in the dictionary. Therefore we have a way to break test1 into words and we should not throw an exception. That's why we design this testcase.

**Comment by hard-fault** [comment]
> > Review from Team 17:
> > test1 should throw an exception as the apostrophe isn't an expected symbol for the wordbreak tokenizer. The TA clarified this on slack.
> 
> Hi, thank you for advice~
> Do you mean the TA said on slack that "If the input contains punctuations, then your algorithm should not find any possible way and then throw an exception"? However, the apostrophe is not among punctuations, and also there are several words like "i'm 300000", "couldn't 300000" and "can't 300000" in the dictionary. Therefore we have a way to break test1 into words and we should not throw an exception. That's why we design this testcase.

That's right. There are some words in dictionary that allow apostrophe character.

**Comment by omidkv** [comment]
Review from team 14:

I think all your tests look good. We didn't see the words with the apostrophe at the end so your first test case is pretty good.  

The only thing that I see that needs to be fixed is in test 3 the kind of exception that you are checking for. As of writing this comment, this hasn't been confirmed on slack but in class on Tuesday, I believe that Zuozhi said that the exception that should be thrown is a Runtime exception, not an illegal argument exception.

**Pull request merged**
