### PR TITLE
[P4 tests] [Team 6] Get Document Frequency

### PR DESCRIPTION
**Pull request by zhongwew**
- What's your team number?
Team 6

- What is the functionality being tested?
Get Document Frequency

- Describe your tests briefly:
Test1 tests given different keywords, check if function can return correct frequency in different segments
Test2 tests given a specific keyword, check if the sum of frequency of different segments is accurate

- Does each test case have comments/documentation?
Yes

### CODE REVIEW

**Comment by chenghz4** [comment]
Nice work, but there are some problem.
1. It would be better if you use PunctuationTokenizer instead of WordBreaker as an analyzer. When I test your code, the wordbreaker will throw an exception(cannot break the word). So I think you should use PunctuationTokenizer.
2.  In your code line 42, you redefine another invertedlist_manager, which does not make sense.
3. It would be better if you add a test scenario with merge
4. You should only change the Testcase file.

**Comment by zhongwew** [comment]
> Nice work, but there are some problem.
> 
> 1. It would be better if you use PunctuationTokenizer instead of WordBreaker as an analyzer. When I test your code, the wordbreaker will throw an exception(cannot break the word). So I think you should use PunctuationTokenizer.
> 2. In your code line 42, you redefine another invertedlist_manager, which does not make sense.
> 3. It would be better if you add a test scenario with merge
> 4. You should only change the Testcase file.

**Comment by zhongwew** [comment]
> Nice work, but there are some problem.
> 
> 1. It would be better if you use PunctuationTokenizer instead of WordBreaker as an analyzer. When I test your code, the wordbreaker will throw an exception(cannot break the word). So I think you should use PunctuationTokenizer.
> 2. In your code line 42, you redefine another invertedlist_manager, which does not make sense.
> 3. It would be better if you add a test scenario with merge
> 4. You should only change the Testcase file.

**Comment by zhongwew** [comment]
> Nice work, but there are some problem.
> 
> 1. It would be better if you use PunctuationTokenizer instead of WordBreaker as an analyzer. When I test your code, the wordbreaker will throw an exception(cannot break the word). So I think you should use PunctuationTokenizer.
> 2. In your code line 42, you redefine another invertedlist_manager, which does not make sense.
> 3. It would be better if you add a test scenario with merge
> 4. You should only change the Testcase file.

Bug fixed, thanks for feedback.

**Comment by hanluc** [comment]
The test case seems good to me. It helped me to find some bugs there and I think it's ready for merge. Thanks!

**Pull request merged**
